with-expecter: true
dir: "tests/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/zatekoja/Patientpricediscoverydesign/backend/internal/domain/repositories:
    interfaces:
      FacilityRepository:
      FacilitySearchRepository:
      ProcedureRepository:
      FacilityProcedureRepository:
      AppointmentRepository:
      AvailabilityRepository:
      InsuranceRepository:
      UserRepository:
      ReviewRepository:
  github.com/zatekoja/Patientpricediscoverydesign/backend/internal/domain/providers:
    interfaces:
      GeolocationProvider:
      CacheProvider:
  github.com/zatekoja/Patientpricediscoverydesign/backend/internal/query/services:
    interfaces:
      SearchAdapter:
      QueryCacheProvider:
