import { metrics } from '@opentelemetry/api';

const meter = metrics.getMeter('patient-price-discovery-provider', '1.0.0');

const providerSyncCount = meter.createCounter('provider.sync.count', {
  description: 'Number of provider sync attempts',
});
const providerSyncDuration = meter.createHistogram('provider.sync.duration_ms', {
  description: 'Duration of provider sync operations',
  unit: 'ms',
});
const providerRecordsProcessed = meter.createCounter('provider.records.processed', {
  description: 'Number of records processed by provider syncs',
});

const schedulerRunCount = meter.createCounter('scheduler.job.run', {
  description: 'Number of scheduler job runs',
});
const schedulerSkipCount = meter.createCounter('scheduler.job.skipped', {
  description: 'Number of scheduler job runs skipped due to overlap',
});
const schedulerDuration = meter.createHistogram('scheduler.job.duration_ms', {
  description: 'Duration of scheduler job execution',
  unit: 'ms',
});

const apiRequestCount = meter.createCounter('api.request.count', {
  description: 'API request count',
});
const apiRequestDuration = meter.createHistogram('api.request.duration_ms', {
  description: 'API request duration',
  unit: 'ms',
});

const tagGenerationCount = meter.createCounter('provider.tag_generation.count', {
  description: 'Number of tag generation attempts',
});
const tagGenerationErrors = meter.createCounter('provider.tag_generation.error.count', {
  description: 'Number of tag generation errors',
});
const tagGenerationDuration = meter.createHistogram('provider.tag_generation.duration_ms', {
  description: 'Duration of tag generation per item',
  unit: 'ms',
});
const tagsGenerated = meter.createCounter('provider.tags.generated', {
  description: 'Number of tags generated by LLM provider',
});

const providerRecordsPerFacility = meter.createHistogram('provider.records.per_facility', {
  description: 'Number of records ingested per facility',
  unit: 'records',
});

const providerPriceValue = meter.createHistogram('provider.price.value', {
  description: 'Distribution of price values ingested by provider',
});

const providerPriceRange = meter.createHistogram('provider.price.range', {
  description: 'Range of price values per sync batch',
});

const providerTagCoverage = meter.createHistogram('provider.tag.coverage', {
  description: 'Ratio of records with tags present',
});

const providerMissingFieldCount = meter.createCounter('provider.missing_field.count', {
  description: 'Count of missing required fields in provider data',
});

type ProviderSyncState = {
  lastSyncMs?: number;
};

const providerSyncState = new Map<string, ProviderSyncState>();

const providerLastSyncAgeSeconds = meter.createObservableGauge('provider.last_sync_age_seconds', {
  description: 'Seconds since the last successful provider sync',
});

const providerDataFreshnessDays = meter.createObservableGauge('provider.data.freshness_days', {
  description: 'Days since the last successful provider sync',
});

providerLastSyncAgeSeconds.addCallback((observableResult) => {
  const now = Date.now();
  for (const [provider, state] of providerSyncState.entries()) {
    if (!state.lastSyncMs) {
      continue;
    }
    const ageSeconds = Math.max(0, (now - state.lastSyncMs) / 1000);
    observableResult.observe(ageSeconds, { provider });
  }
});

providerDataFreshnessDays.addCallback((observableResult) => {
  const now = Date.now();
  for (const [provider, state] of providerSyncState.entries()) {
    if (!state.lastSyncMs) {
      continue;
    }
    const ageDays = Math.max(0, (now - state.lastSyncMs) / (1000 * 60 * 60 * 24));
    observableResult.observe(ageDays, { provider });
  }
});

export function recordProviderSyncMetrics(params: {
  provider: string;
  success: boolean;
  recordsProcessed: number;
  durationMs: number;
  timestamp?: Date;
}): void {
  providerSyncCount.add(1, { provider: params.provider, success: String(params.success) });
  providerSyncDuration.record(params.durationMs, { provider: params.provider });
  providerRecordsProcessed.add(params.recordsProcessed, { provider: params.provider });
  if (params.success) {
    const ts = params.timestamp ? params.timestamp.getTime() : Date.now();
    providerSyncState.set(params.provider, { lastSyncMs: ts });
  }
}

export function recordSchedulerRun(params: {
  job: string;
  success?: boolean;
  durationMs?: number;
}): void {
  schedulerRunCount.add(1, {
    job: params.job,
    success: params.success === undefined ? 'unknown' : String(params.success),
  });
  if (params.durationMs !== undefined) {
    schedulerDuration.record(params.durationMs, { job: params.job });
  }
}

export function recordSchedulerSkip(job: string): void {
  schedulerSkipCount.add(1, { job });
}

export function recordApiRequest(params: {
  method: string;
  path: string;
  status: number;
  durationMs: number;
}): void {
  apiRequestCount.add(1, {
    method: params.method,
    path: params.path,
    status: params.status,
  });
  apiRequestDuration.record(params.durationMs, {
    method: params.method,
    path: params.path,
    status: params.status,
  });
}

export function recordTagGeneration(params: {
  provider: string;
  durationMs: number;
  tags: number;
  success: boolean;
}): void {
  tagGenerationCount.add(1, { provider: params.provider, success: String(params.success) });
  tagGenerationDuration.record(params.durationMs, { provider: params.provider });
  if (params.tags > 0) {
    tagsGenerated.add(params.tags, { provider: params.provider });
  }
  if (!params.success) {
    tagGenerationErrors.add(1, { provider: params.provider });
  }
}

export interface ProviderRecordLike {
  facilityName?: string;
  procedureCode?: string;
  procedureDescription?: string;
  price?: number;
  currency?: string;
  effectiveDate?: Date | string;
  tags?: string[];
}

export function recordProviderDataMetrics(params: {
  provider: string;
  records: ProviderRecordLike[];
}): void {
  const { provider, records } = params;
  if (!records || records.length === 0) {
    return;
  }

  const facilityCounts = new Map<string, number>();
  const missingFieldCounts: Record<string, number> = {
    facilityName: 0,
    procedureCode: 0,
    procedureDescription: 0,
    price: 0,
    effectiveDate: 0,
  };

  let taggedCount = 0;
  let minPrice: number | null = null;
  let maxPrice: number | null = null;

  for (const record of records) {
    const facilityName = (record.facilityName || '').trim();
    if (!facilityName) {
      missingFieldCounts.facilityName += 1;
    } else {
      facilityCounts.set(facilityName, (facilityCounts.get(facilityName) || 0) + 1);
    }

    if (!record.procedureCode || String(record.procedureCode).trim().length === 0) {
      missingFieldCounts.procedureCode += 1;
    }
    if (!record.procedureDescription || String(record.procedureDescription).trim().length === 0) {
      missingFieldCounts.procedureDescription += 1;
    }

    const price = typeof record.price === 'number' ? record.price : Number(record.price);
    if (!Number.isFinite(price)) {
      missingFieldCounts.price += 1;
    } else {
      const currency = record.currency || 'unknown';
      providerPriceValue.record(price, { provider, currency });
      if (minPrice === null || price < minPrice) {
        minPrice = price;
      }
      if (maxPrice === null || price > maxPrice) {
        maxPrice = price;
      }
    }

    const effectiveDate = record.effectiveDate;
    if (!effectiveDate) {
      missingFieldCounts.effectiveDate += 1;
    } else {
      const parsed =
        effectiveDate instanceof Date ? effectiveDate : new Date(effectiveDate);
      if (Number.isNaN(parsed.getTime())) {
        missingFieldCounts.effectiveDate += 1;
      }
    }

    if (record.tags && record.tags.length > 0) {
      taggedCount += 1;
    }
  }

  for (const [facility, count] of facilityCounts.entries()) {
    providerRecordsPerFacility.record(count, { provider, facility });
  }

  const tagCoverage = taggedCount / records.length;
  providerTagCoverage.record(tagCoverage, { provider });

  for (const [field, count] of Object.entries(missingFieldCounts)) {
    if (count > 0) {
      providerMissingFieldCount.add(count, { provider, field });
    }
  }

  if (minPrice !== null && maxPrice !== null) {
    const currency = records.find((record) => record.currency)?.currency || 'unknown';
    providerPriceRange.record(maxPrice - minPrice, { provider, currency });
  }
}
