import { metrics } from '@opentelemetry/api';

const meter = metrics.getMeter('patient-price-discovery-provider', '1.0.0');

const providerSyncCount = meter.createCounter('provider.sync.count', {
  description: 'Number of provider sync attempts',
});
const providerSyncDuration = meter.createHistogram('provider.sync.duration_ms', {
  description: 'Duration of provider sync operations',
  unit: 'ms',
});
const providerRecordsProcessed = meter.createCounter('provider.records.processed', {
  description: 'Number of records processed by provider syncs',
});

const schedulerRunCount = meter.createCounter('scheduler.job.run', {
  description: 'Number of scheduler job runs',
});
const schedulerSkipCount = meter.createCounter('scheduler.job.skipped', {
  description: 'Number of scheduler job runs skipped due to overlap',
});
const schedulerDuration = meter.createHistogram('scheduler.job.duration_ms', {
  description: 'Duration of scheduler job execution',
  unit: 'ms',
});

const apiRequestCount = meter.createCounter('api.request.count', {
  description: 'API request count',
});
const apiRequestDuration = meter.createHistogram('api.request.duration_ms', {
  description: 'API request duration',
  unit: 'ms',
});

const tagGenerationCount = meter.createCounter('provider.tag_generation.count', {
  description: 'Number of tag generation attempts',
});
const tagGenerationErrors = meter.createCounter('provider.tag_generation.error.count', {
  description: 'Number of tag generation errors',
});
const tagGenerationDuration = meter.createHistogram('provider.tag_generation.duration_ms', {
  description: 'Duration of tag generation per item',
  unit: 'ms',
});
const tagsGenerated = meter.createCounter('provider.tags.generated', {
  description: 'Number of tags generated by LLM provider',
});

export function recordProviderSyncMetrics(params: {
  provider: string;
  success: boolean;
  recordsProcessed: number;
  durationMs: number;
}): void {
  providerSyncCount.add(1, { provider: params.provider, success: String(params.success) });
  providerSyncDuration.record(params.durationMs, { provider: params.provider });
  providerRecordsProcessed.add(params.recordsProcessed, { provider: params.provider });
}

export function recordSchedulerRun(params: {
  job: string;
  success?: boolean;
  durationMs?: number;
}): void {
  schedulerRunCount.add(1, {
    job: params.job,
    success: params.success === undefined ? 'unknown' : String(params.success),
  });
  if (params.durationMs !== undefined) {
    schedulerDuration.record(params.durationMs, { job: params.job });
  }
}

export function recordSchedulerSkip(job: string): void {
  schedulerSkipCount.add(1, { job });
}

export function recordApiRequest(params: {
  method: string;
  path: string;
  status: number;
  durationMs: number;
}): void {
  apiRequestCount.add(1, {
    method: params.method,
    path: params.path,
    status: params.status,
  });
  apiRequestDuration.record(params.durationMs, {
    method: params.method,
    path: params.path,
    status: params.status,
  });
}

export function recordTagGeneration(params: {
  provider: string;
  durationMs: number;
  tags: number;
  success: boolean;
}): void {
  tagGenerationCount.add(1, { provider: params.provider, success: String(params.success) });
  tagGenerationDuration.record(params.durationMs, { provider: params.provider });
  if (params.tags > 0) {
    tagsGenerated.add(params.tags, { provider: params.provider });
  }
  if (!params.success) {
    tagGenerationErrors.add(1, { provider: params.provider });
  }
}
