package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"

	"github.com/zatekoja/Patientpricediscoverydesign/backend/internal/domain/entities"
	"github.com/zatekoja/Patientpricediscoverydesign/backend/internal/domain/repositories"
	"github.com/zatekoja/Patientpricediscoverydesign/backend/internal/graphql/generated"
)

// Facility is the resolver for the facility field.
func (r *appointmentResolver) Facility(ctx context.Context, obj *entities.Appointment) (*entities.Facility, error) {
	panic(fmt.Errorf("not implemented: Facility - facility"))
}

// Procedure is the resolver for the procedure field.
func (r *appointmentResolver) Procedure(ctx context.Context, obj *entities.Appointment) (*entities.Procedure, error) {
	panic(fmt.Errorf("not implemented: Procedure - procedure"))
}

// ProviderName is the resolver for the providerName field.
func (r *appointmentResolver) ProviderName(ctx context.Context, obj *entities.Appointment) (string, error) {
	panic(fmt.Errorf("not implemented: ProviderName - providerName"))
}

// AppointmentDate is the resolver for the appointmentDate field.
func (r *appointmentResolver) AppointmentDate(ctx context.Context, obj *entities.Appointment) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: AppointmentDate - appointmentDate"))
}

// Duration is the resolver for the duration field.
func (r *appointmentResolver) Duration(ctx context.Context, obj *entities.Appointment) (int, error) {
	panic(fmt.Errorf("not implemented: Duration - duration"))
}

// Price is the resolver for the price field.
func (r *appointmentResolver) Price(ctx context.Context, obj *entities.Appointment) (float64, error) {
	panic(fmt.Errorf("not implemented: Price - price"))
}

// InsuranceProvider is the resolver for the insuranceProvider field.
func (r *appointmentResolver) InsuranceProvider(ctx context.Context, obj *entities.Appointment) (*entities.InsuranceProvider, error) {
	panic(fmt.Errorf("not implemented: InsuranceProvider - insuranceProvider"))
}

// FacilityType is the resolver for the facilityType field.
func (r *facilityResolver) FacilityType(ctx context.Context, obj *entities.Facility) (generated.FacilityType, error) {
	panic(fmt.Errorf("not implemented: FacilityType - facilityType"))
}

// Contact is the resolver for the contact field.
func (r *facilityResolver) Contact(ctx context.Context, obj *entities.Facility) (*generated.Contact, error) {
	panic(fmt.Errorf("not implemented: Contact - contact"))
}

// AcceptsNewPatients is the resolver for the acceptsNewPatients field.
func (r *facilityResolver) AcceptsNewPatients(ctx context.Context, obj *entities.Facility) (bool, error) {
	panic(fmt.Errorf("not implemented: AcceptsNewPatients - acceptsNewPatients"))
}

// HasEmergency is the resolver for the hasEmergency field.
func (r *facilityResolver) HasEmergency(ctx context.Context, obj *entities.Facility) (bool, error) {
	panic(fmt.Errorf("not implemented: HasEmergency - hasEmergency"))
}

// HasParking is the resolver for the hasParking field.
func (r *facilityResolver) HasParking(ctx context.Context, obj *entities.Facility) (bool, error) {
	panic(fmt.Errorf("not implemented: HasParking - hasParking"))
}

// WheelchairAccessible is the resolver for the wheelchairAccessible field.
func (r *facilityResolver) WheelchairAccessible(ctx context.Context, obj *entities.Facility) (bool, error) {
	panic(fmt.Errorf("not implemented: WheelchairAccessible - wheelchairAccessible"))
}

// PriceRange is the resolver for the priceRange field.
func (r *facilityResolver) PriceRange(ctx context.Context, obj *entities.Facility) (*generated.PriceRange, error) {
	panic(fmt.Errorf("not implemented: PriceRange - priceRange"))
}

// InsuranceProviders is the resolver for the insuranceProviders field.
func (r *facilityResolver) InsuranceProviders(ctx context.Context, obj *entities.Facility) ([]*entities.InsuranceProvider, error) {
	panic(fmt.Errorf("not implemented: InsuranceProviders - insuranceProviders"))
}

// Specialties is the resolver for the specialties field.
func (r *facilityResolver) Specialties(ctx context.Context, obj *entities.Facility) ([]*generated.Specialty, error) {
	panic(fmt.Errorf("not implemented: Specialties - specialties"))
}

// Procedures is the resolver for the procedures field.
func (r *facilityResolver) Procedures(ctx context.Context, obj *entities.Facility, limit *int, offset *int) (*generated.ProcedureConnection, error) {
	panic(fmt.Errorf("not implemented: Procedures - procedures"))
}

// LanguagesSpoken is the resolver for the languagesSpoken field.
func (r *facilityResolver) LanguagesSpoken(ctx context.Context, obj *entities.Facility) ([]string, error) {
	panic(fmt.Errorf("not implemented: LanguagesSpoken - languagesSpoken"))
}

// AvgWaitTime is the resolver for the avgWaitTime field.
func (r *facilityResolver) AvgWaitTime(ctx context.Context, obj *entities.Facility) (*int, error) {
	panic(fmt.Errorf("not implemented: AvgWaitTime - avgWaitTime"))
}

// NextAvailableSlot is the resolver for the nextAvailableSlot field.
func (r *facilityResolver) NextAvailableSlot(ctx context.Context, obj *entities.Facility) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: NextAvailableSlot - nextAvailableSlot"))
}

// ProviderType is the resolver for the providerType field.
func (r *insuranceProviderResolver) ProviderType(ctx context.Context, obj *entities.InsuranceProvider) (generated.InsuranceType, error) {
	panic(fmt.Errorf("not implemented: ProviderType - providerType"))
}

// CoverageStates is the resolver for the coverageStates field.
func (r *insuranceProviderResolver) CoverageStates(ctx context.Context, obj *entities.InsuranceProvider) ([]string, error) {
	panic(fmt.Errorf("not implemented: CoverageStates - coverageStates"))
}

// FacilitiesCount is the resolver for the facilitiesCount field.
func (r *insuranceProviderResolver) FacilitiesCount(ctx context.Context, obj *entities.InsuranceProvider) (int, error) {
	panic(fmt.Errorf("not implemented: FacilitiesCount - facilitiesCount"))
}

// ProceduresCount is the resolver for the proceduresCount field.
func (r *insuranceProviderResolver) ProceduresCount(ctx context.Context, obj *entities.InsuranceProvider) (int, error) {
	panic(fmt.Errorf("not implemented: ProceduresCount - proceduresCount"))
}

// Category is the resolver for the category field.
func (r *procedureResolver) Category(ctx context.Context, obj *entities.Procedure) (generated.ProcedureCategory, error) {
	panic(fmt.Errorf("not implemented: Category - category"))
}

// Price is the resolver for the price field.
func (r *procedureResolver) Price(ctx context.Context, obj *entities.Procedure) (float64, error) {
	panic(fmt.Errorf("not implemented: Price - price"))
}

// Duration is the resolver for the duration field.
func (r *procedureResolver) Duration(ctx context.Context, obj *entities.Procedure) (int, error) {
	panic(fmt.Errorf("not implemented: Duration - duration"))
}

// RequiresReferral is the resolver for the requiresReferral field.
func (r *procedureResolver) RequiresReferral(ctx context.Context, obj *entities.Procedure) (bool, error) {
	panic(fmt.Errorf("not implemented: RequiresReferral - requiresReferral"))
}

// PreparationRequired is the resolver for the preparationRequired field.
func (r *procedureResolver) PreparationRequired(ctx context.Context, obj *entities.Procedure) (bool, error) {
	panic(fmt.Errorf("not implemented: PreparationRequired - preparationRequired"))
}

// Facility is the resolver for the facility field.
func (r *procedureResolver) Facility(ctx context.Context, obj *entities.Procedure) (*entities.Facility, error) {
	panic(fmt.Errorf("not implemented: Facility - facility"))
}

// InsuranceCoverage is the resolver for the insuranceCoverage field.
func (r *procedureResolver) InsuranceCoverage(ctx context.Context, obj *entities.Procedure) ([]*entities.InsuranceProvider, error) {
	panic(fmt.Errorf("not implemented: InsuranceCoverage - insuranceCoverage"))
}

// Facility is the resolver for the facility field.
func (r *queryResolver) Facility(ctx context.Context, id string) (*entities.Facility, error) {
	cacheKey := "facility:" + id

	// Try cache first
	if r.cache != nil {
		cached, err := r.cache.Get(ctx, cacheKey)
		if err == nil && cached != nil {
			if facility, ok := cached.(*entities.Facility); ok {
				return facility, nil
			}
		}
	}

	// Fall back to database
	facility, err := r.facilityRepo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}

	// Cache result
	if r.cache != nil {
		_ = r.cache.Set(ctx, cacheKey, facility, 5*time.Minute)
	}

	return facility, nil
}

// Facilities is the resolver for the facilities field.
func (r *queryResolver) Facilities(ctx context.Context, filter generated.FacilitySearchInput) (*generated.FacilitySearchResult, error) {
	// Build search params from filter
	params := repositories.SearchParams{
		Limit:  20,
		Offset: 0,
	}

	if filter.Location != nil {
		params.Latitude = filter.Location.Latitude
		params.Longitude = filter.Location.Longitude
	}
	params.RadiusKm = filter.RadiusKm

	if filter.Limit != nil {
		params.Limit = *filter.Limit
	}
	if filter.Offset != nil {
		params.Offset = *filter.Offset
	}
	if filter.MaxPrice != nil {
		params.MaxPrice = filter.MaxPrice
	}
	if filter.MinPrice != nil {
		params.MinPrice = filter.MinPrice
	}

	// Search via Typesense
	facilities, err := r.searchAdapter.Search(ctx, params)
	if err != nil {
		// Fallback to database
		facilities, err = r.facilityRepo.Search(ctx, params)
		if err != nil {
			return nil, err
		}
	}

	return &generated.FacilitySearchResult{
		Facilities: facilities,
		TotalCount: len(facilities),
		SearchTime: 0, // TODO: measure actual search time
		Facets:     &generated.FacilityFacets{},
		Pagination: &generated.PaginationInfo{
			HasNextPage:     len(facilities) >= params.Limit,
			HasPreviousPage: params.Offset > 0,
			CurrentPage:     (params.Offset / params.Limit) + 1,
			TotalPages:      1, // TODO: calculate properly
			Limit:           params.Limit,
			Offset:          params.Offset,
		},
	}, nil
}

// SearchFacilities is the resolver for the searchFacilities field.
func (r *queryResolver) SearchFacilities(ctx context.Context, query string, location generated.LocationInput, radiusKm *float64, filters *generated.FacilitySearchInput) (*generated.FacilitySearchResult, error) {
	// Build search params
	params := repositories.SearchParams{
		Latitude:  location.Latitude,
		Longitude: location.Longitude,
		Limit:     20,
		Offset:    0,
	}

	if radiusKm != nil {
		params.RadiusKm = *radiusKm
	} else {
		params.RadiusKm = 50 // default
	}

	// Apply filters if provided
	if filters != nil {
		if filters.Limit != nil {
			params.Limit = *filters.Limit
		}
		if filters.Offset != nil {
			params.Offset = *filters.Offset
		}
		if filters.MaxPrice != nil {
			params.MaxPrice = filters.MaxPrice
		}
		if filters.MinPrice != nil {
			params.MinPrice = filters.MinPrice
		}
	}

	// Search via Typesense
	facilities, err := r.searchAdapter.Search(ctx, params)
	if err != nil {
		// Fallback to database
		facilities, err = r.facilityRepo.Search(ctx, params)
		if err != nil {
			return nil, err
		}
	}

	return &generated.FacilitySearchResult{
		Facilities: facilities,
		TotalCount: len(facilities),
		SearchTime: 0,
		Facets:     &generated.FacilityFacets{},
		Pagination: &generated.PaginationInfo{
			HasNextPage:     len(facilities) >= params.Limit,
			HasPreviousPage: params.Offset > 0,
			CurrentPage:     (params.Offset / params.Limit) + 1,
			TotalPages:      1,
			Limit:           params.Limit,
			Offset:          params.Offset,
		},
	}, nil
}

// FacilitySuggestions is the resolver for the facilitySuggestions field.
func (r *queryResolver) FacilitySuggestions(ctx context.Context, query string, location generated.LocationInput, limit *int) ([]*generated.FacilitySuggestion, error) {
	panic(fmt.Errorf("not implemented: FacilitySuggestions - facilitySuggestions"))
}

// Procedure is the resolver for the procedure field.
func (r *queryResolver) Procedure(ctx context.Context, id string) (*entities.Procedure, error) {
	panic(fmt.Errorf("not implemented: Procedure - procedure"))
}

// Procedures is the resolver for the procedures field.
func (r *queryResolver) Procedures(ctx context.Context, filter generated.ProcedureSearchInput) (*generated.ProcedureConnection, error) {
	panic(fmt.Errorf("not implemented: Procedures - procedures"))
}

// Appointment is the resolver for the appointment field.
func (r *queryResolver) Appointment(ctx context.Context, id string) (*entities.Appointment, error) {
	panic(fmt.Errorf("not implemented: Appointment - appointment"))
}

// Appointments is the resolver for the appointments field.
func (r *queryResolver) Appointments(ctx context.Context, filter generated.AppointmentSearchInput) ([]*entities.Appointment, error) {
	panic(fmt.Errorf("not implemented: Appointments - appointments"))
}

// InsuranceProvider is the resolver for the insuranceProvider field.
func (r *queryResolver) InsuranceProvider(ctx context.Context, id string) (*entities.InsuranceProvider, error) {
	panic(fmt.Errorf("not implemented: InsuranceProvider - insuranceProvider"))
}

// InsuranceProviders is the resolver for the insuranceProviders field.
func (r *queryResolver) InsuranceProviders(ctx context.Context, isActive *bool, state *string, limit *int, offset *int) ([]*entities.InsuranceProvider, error) {
	panic(fmt.Errorf("not implemented: InsuranceProviders - insuranceProviders"))
}

// FacilityStats is the resolver for the facilityStats field.
func (r *queryResolver) FacilityStats(ctx context.Context) (*generated.FacilityStats, error) {
	panic(fmt.Errorf("not implemented: FacilityStats - facilityStats"))
}

// PriceComparison is the resolver for the priceComparison field.
func (r *queryResolver) PriceComparison(ctx context.Context, procedureCode string, location generated.LocationInput, radiusKm float64) (*generated.PriceComparisonResult, error) {
	panic(fmt.Errorf("not implemented: PriceComparison - priceComparison"))
}

// Appointment returns generated.AppointmentResolver implementation.
func (r *Resolver) Appointment() generated.AppointmentResolver { return &appointmentResolver{r} }

// Facility returns generated.FacilityResolver implementation.
func (r *Resolver) Facility() generated.FacilityResolver { return &facilityResolver{r} }

// InsuranceProvider returns generated.InsuranceProviderResolver implementation.
func (r *Resolver) InsuranceProvider() generated.InsuranceProviderResolver {
	return &insuranceProviderResolver{r}
}

// Procedure returns generated.ProcedureResolver implementation.
func (r *Resolver) Procedure() generated.ProcedureResolver { return &procedureResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type appointmentResolver struct{ *Resolver }
type facilityResolver struct{ *Resolver }
type insuranceProviderResolver struct{ *Resolver }
type procedureResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
